# Site settings
title: Rainbow-Prince's Blog
SEOTitle: Rainbow-Prince 的博客 | Rainbow-Prince's Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "这里是 @Rainbow-Prince 的个人博客，带你走进我的世界 | 做一个不受拘束的浪子吧"
keyword: "Rainbow-Prince, 蒸鱼🐟, @Rainbow-Prince"
url: "https://huangxuan.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
#RSS: false
#weibo_username: huxpro
zhihu_username: 快乐的小狗
github_username: Rainbow-prince
#twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:  # 不影响jekyll serve实时预览的文件
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
    .idea/,
    .obsidian/,
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: hux
disqus_username: null

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "一个 不受拘束 的浪子 <br> Impossible to win the game for timid rats"
sidebar-avatar: /img/avatar-Rainbow-prince.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 5 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
#page-mathjax: false
page-mathjax: true

# Friends
friends:
  [
#    { title: "乱序（Midare）", href: "http://mida.re/" },
#    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#    { title: "Kun Qian", href: "http://kunq.me" },
#    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#    { title: "SmdCn", href: "http://blog.smdcn.net" },
#    { title: "JiyinYiyong", href: "http://tiye.me/" },
#    { title: "DHong Say", href: "http://dhong.co" },
#    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
