# Site settings
title: Xiao Nan 's Blog  # 网站标题
SEOTitle: 肖楠的博客 | Xiao Nan 's Blog  # SEO优化标题
header-img: img/home-bg.jpg  # 网站头部图片
email: xiaon24@gmail.tsinghua.com  # 联系邮箱
description: "这里是肖楠的个人博客，很高兴遇见你"  # 网站描述

# Publish posts or collection documents with a future date.
future: true  # 允许发布将来日期的文章

# Build settings
highlighter: rouge  # 代码高亮工具
permalink: pretty  # 永久链接样式
paginate: 10  # 每页显示的文章数
exclude:  # 构建时排除的文件和文件夹
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true  # 是否启用锚点JS（用于文章内部跳转）

# Gems
plugins: [jekyll-paginate]  # 使用的Jekyll插件，例如分页插件

# Markdown settings
markdown: kramdown  # 使用kramdown作为Markdown解析器
kramdown:
  input: GFM  # 使用GitHub风格的Markdown
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: true  # 是否启用侧边栏
sidebar-about-description: "要做一个有 swag 的程序员"  # 侧边栏个人描述
sidebar-avatar: img/profile.jpg  # 侧边栏头像图片URL

# # Friends
# friends:  # 友情链接列表
#   [
#     { title: "Xiao Nan's Main Blog", href: "http://xiaonan.me" },
#   ]
