# Site settings
title: Dann Blog
SEOTitle: 談楊的博客 | Dann Blog
header-img: img/home-bg.jpg
email: dannsouyou@gmail.com
description: "关于R與Python、詩歌与戲曲、根本佛法 | 談楊，Data Science, R & Python, NGO, Buddhist | 不著調的人"
keyword: "談楊, dannsaoyou, Dann談楊, Dann, 佛法, 上座部, @dannsaoyou, 談楊的博客, Dann Blog, 博客, 个人网站, 公益組織,教育,NGO"
            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     
#zhihu_username:     
#github_username:    mettadann
twitter_username:  dannsaoyou
#facebook_username:  
linkedin_username:  yang-tan-391



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-79014677-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "搗鼓數據，謝謝筆記，學學佛法。一切輪迴終有盡頭"
sidebar-avatar: /img/avatar-dann.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


#the bg size 1900*870
