name: Setup Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_ruby:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          ./install.sh

      - name: Install Ruby 3.1.4 using ruby-build
        run: |
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Verify Ruby installation
        run: ruby -v
