name: Reset Notion Sync
on:
  workflow_dispatch:  # 支持手动触发

jobs:
  reset:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Clean cache and posts
        run: |
          # 删除缓存文件
          rm -f .notion_cache
          
          # 清空_posts目录但保留.gitkeep（如有）
          find _posts -type f ! -name '.gitkeep' -delete
          
          # 创建初始提交文件（可选）
          touch _posts/.gitkeep

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔨 Reset Notion Sync State"
          file_pattern: |
            .notion_cache
            _posts/
